# -*- coding: utf-8 -*-
"""
Created on Sat Nov 11 20:42:12 2023

@author: HP
"""

# ----------Instructions:
    # Part 1: Data Exploration with Pandas
# Load the provided dataset into a pandas dataframe
# Use pandas to explore the dataset. For example, you might start by using the head() and info() methods to get an overview of the data.
# Look for missing values in the dataset. You can use the isnull() method to identify missing values.
# Use pandas to calculate some summary statistics for the dataset. For example, you might use the describe() method to get summary statistics for the numerical columns in the dataset.
    # Part 2: Data Exploration with ydata-Profiling
# Use ydata-profiling to generate a report of the provided dataset.
# Look for missing values in the dataset. You can use the report generated by ydata-profiling to identify missing values.
# Look for correlations between different columns in the dataset. You can use the report generated by ydata-profiling to identify correlations between different columns.
# Identify any outliers or unusual values in the dataset. You can use the report generated by ydata-profiling to identify any outliers or unusual values.
#-----------------Summary:
    # At the end of this exercise, write a summary of your findings. Did you find any interesting patterns or correlations in the data? Were there any issues or challenges you encountered while exploring the dataset? Use your summary to reflect on your experience using pandas and ydata-profiling to explore and understand a new dataset.
    
    
#-----------------------Part 1: Data Exploration with Pandas
import pandas as pd
import sweetviz as sv
import seaborn as sns
# Load the provided dataset into a pandas dataframe
data = "C:/Users/HP/Downloads/Tunisair_flights_dataset.csv"
dataset = pd.read_csv(data)
# Use pandas to explore the dataset. For example, you might start by using the head() and info() methods to get an overview of the data.
dataset_head = dataset.head(11) # Shows you the first 5 rows in the data
dataset_tail = dataset.tail(11) # Shows you the last 5 rows in the data
dataset_desc_all = dataset.describe(include = "all") # More simple statistics that descibes the Parameters in each column
dataset_total_null = dataset.isnull().sum().sum()
dataset_info = dataset.info()
dataset_distinct_count = dataset.nunique()
dataset_corr = dataset.iloc[:, 8].corr(dataset.iloc[:, 8])
# Look for missing values in the dataset. You can use the isnull() method to identify missing values.
missing_data = dataset.isnull().any()
# Use pandas to calculate some summary statistics for the dataset. For example, you might use the describe() method to get summary statistics for the numerical columns in the dataset.
dataset_desc = dataset.describe()
#-----------------------Part 2: Data Exploration with ydata-Profiling
# Use ydata-profiling to generate a report of the provided dataset.
my_report = sv.analyze(dataset)
my_report.show_html()
# Look for missing values in the dataset. You can use the report generated by ydata-profiling to identify missing values.:
    # From the report given there are no missing values.
# Look for correlations between different columns in the dataset. You can use the report generated by ydata-profiling to identify correlations between different columns.
# The correlation between the columns, "Air_craft code" and "Status":
    # from the result shown in the report sheet, it indicates that the two columns are correlated in a positive direction. 
    # Smae thing goes for "Arrival delay" and "Status" and,
    # "Air_craft code" and "Arrival delay"
# Identify any outliers or unusual values in the dataset. You can use the report generated by ydata-profiling to identify any outliers or unusual values.
sns.set_theme()
sns.displot(data=dataset).set(title="Distribution of Tunisian flight", xlabel="Arrival delay")
# there are no outliers in the report generated
#----------------------------Summary:
    # At the end of this exercise, write a summary of your findings. Did you find any interesting patterns or correlations in the data? Were there any issues or challenges you encountered while exploring the dataset? Use your summary to reflect on your experience using pandas and ydata-profiling to explore and understand a new dataset.
    

